### ISSUE TITLE
what is the salt value for Argon2id?

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-opaque#400] opened 2023-03-13 23:21 UTC
In the parametrization for KSF=Argon2id there is no specification for the salt parameter expected by Argon2id.

According to [spec](https://www.password-hashing.net/argon2-specs.pdf): "...salt must be at least 8 bytes, and 16 for password hashing..."

**Comment by stef** [comment] 2023-03-14 01:18
duplicate of https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/398 ?

**Comment by daxpedda** [comment] 2023-03-21 12:04
> According to [spec](https://www.password-hashing.net/argon2-specs.pdf): "...salt must be at least 8 bytes, and 16 for password hashing..."

The IETF spec, the one this spec relies on, doesn't actually enforce a salt:
https://www.rfc-editor.org/rfc/rfc9106#section-3.1-2.2
> Nonce S, which is a salt for password hashing applications. It MUST have a length not greater than 2^(32)-1 bytes. 16 bytes is RECOMMENDED for password hashing. The salt SHOULD be unique for each password.

**Closed** 2023-03-22 12:25 UTC
