### ISSUE TITLE
User enumeration on registration

### ISSUE THREAD

**Issue by mitar** [cfrg/draft-irtf-cfrg-opaque#388] opened 2023-02-26 15:37 UTC
Reading the spec, I see that there is in few places explained how to prevent user enumeration at login time, e.g., by returning fake envelops to the client. But I also see that user enumeration on registration is not really addressed and just rate limiting is suggested as a mitigation. To me this means that attacker would simply be doing user enumeration through registration and not login. If both are not protected attacker picks the unprotected path, not the protected path.

I think that maybe all this about user enumeration should be removed from the spec. Because as it currently stands you start reading it and you think that OPAQUE is protected against user enumeration and then in the last paragraph of 10.9 you read that it is incomplete and thus not really. Spec should just suggest rate limiting as mitigation both for login and registration.

---

One way to address this could be if there was a way to combine registration and login flows into one flow (potentially with unnecessary messages/data) and client would simply always do the same flow: if user is already registered, they would authenticate to the server, if they are not, they would both register and authenticate to the server. I am not (yet) familiar enough with OPAQUE too see if this would be possible and how, so I am bringing it here.

One way I think it might work is if servers would be constructing envelopes (as it was in JKX18, but without encrypted credentials). Then server could construct a new one if user is not yet registered, or send an existing one if user is already registered. For client there would be no difference and would do the same in both cases.

But this approach seems to enable MITM attack (currently the identity of the server is pinned at the registration time by storing the server public key into the envelope, if I understand correctly). But by using a TLS channel this might be mitigated?

**Comment by mitar** [comment] 2023-02-26 19:54
Having login and registration as one step could also address #392.

**Comment by cyyynthia** [comment] 2023-03-04 20:07
I think you're completely missing the point by assuming only a single threat model applies. In a setting where a form has both a login and registration form, there is no need to prevent enumeration on the login form as the registration form will naturally leak this information.

However, in a setting where the registration is locked behind prior authorization (there is no way to register an account without prior authorization), there is no registration form to target. In these scenarios, having user enumeration protection *does* make sense and the protocol reflects its ready for these use cases, where user enumeration is a concern in your threat model.

This is something that already exists in traditional username/password logins, where accounts can be enumerated via the register form regardless of any protection applied onto your login form.

I'm unsure about what you mean by mixing up both flows as a way to mitigate it. If the user doesn't exist, then the password used during registration will always be valid "first-try", enabling the attacker to know it was a successful registration attempt. Unnecessary traffic would be bad for the efficiency of the protocol, which already is quite heavy on low-end devices considering the password derivation is done by the client in addition of the cryptographic operations going on.

My understanding is that the authentication side of the protocol is capable of being resilient to enumeration attacks, and is documented as such. The registration process is not capable of such resilience due to its very nature, which is also documented as such. It's then up to the users of the protocol to see if these properties fit their threat model, how they must use OPAQUE to fit said threat model, and what additional measures they must take to fully address their threat model.

**Comment by mitar** [comment] 2023-03-05 22:24
Sorry, maybe I was not clear here. My motivation is to have a system where user enumeration is not possible for both login and registration flows. And I know how to do that using standard "send password to the server and hash it there" way of storing passwords. It works by combining registration and login flow into one flow and tie it with one-time code as 2FA. So user is prompted with a form with two fields: email and password. They enter them and press "login or register" button. Now there are three options:

* Account is already registered with that e-mail and password was correct for that account. In that case, user is logged in (or some 2FA is invoked).
* Account is not yet registered with that e-mail, then one-time code is send to the e-mail address and user is asked to enter that code. After entering the correct code, a new account is registered and e-mail address has been validated. It is like usual "activate your account" flow, just combined to prevent enumeration.
  * If user does not have access to the e-mail, no information is leaked to the user about e-mail address having or not an account.
* Account is already registered with that e-mail, but the password is not correct, then one-time code is send to the e-mail address and user is asked to enter that code. After entering the correct code, user is logged in. They can be optionally prompted to reset their password. This low is like usual "reset your password" flow, just combined to prevent enumeration.
  * If user does not know the password, no information is leaked to the user about e-mail address having or not an account.

Now, I am trying to see how could I use OPAQUE and prevent user enumeration both at login and registration time. This is why I am thinking that maybe combining login and registration flows into one flow could help here as well to achieve it.

**Comment by cyyynthia** [comment] 2023-03-06 00:30
I think your approach could be much simpler and better on the users, by still keeping both separate and only applying special treatment to the registration. Having it setup this way is absolutely horrible for the user experience as an invalid password immediately trips an implicit password reset which isn't great.

If you keep both forms separate, you can still treat duplicate registrations as an attempt to password reset, store the hashed password in a temporary place, and have the user confirm the change by email. So a failed login doesn't cause unnecessary noise on the user, while having the registration endpoint not leak anything about the status of that email, and perform the same-ish operations and prevent a possible timing attack.

Applying this to the OPAQUE protocol, in the event of a duplicate registration, store the RegistrationRecord somewhere temporary and send the user a confirmation email, if they want to confirm the password change or not (possibly, word clearly what's going on to avoid confusion, UX stuff blah blah blah). If the change is confirmed, persist the record, otherwise let it expire and discard it from your database.

This allows your flow to have a better UX, better fits the way OPAQUE works, and doesn't leak registered emails on the registration form. Unless I'm missing something.

**Comment by mitar** [comment] 2023-03-06 12:35
> Having it setup this way is absolutely horrible for the user experience as an invalid password immediately trips an implicit password reset which isn't great.

It is not exactly password reset, but login with a code. They do not have to reset the password after the login (but are prompted by a non-modal message that the password was wrong, if they want to reset it). This workflow comes from three insights:

* Users are more and more using password managers, so wrong passwords are rare.
* Those users who do make mistakes are generally those who use site rarely and do not even remember if they do have an account or not. For them it is often a very confused process. They start login, they get their password wrong, then they decide that maybe they do not have an account (they do not remember well), they start registration, registration complains that e-mail is already in use, they go to password reset, etc.
* Most sites use "login with code" for password reset, trusting such login fully (in my system you are prompted with another 2FA if user has it enabled).

So if password reset is already trusted, then it does not really matter if user logged in with (correct) password or just one time code. In fact, they can jump to one time code directly, without messing up the password. :-) And maybe they configured that one time code is not their 2FA, then when they enter the wrong password and get to one time code dialog, they know they messed it up and can go back.

But I have not yet done user studies to test this workflow to see if it is horrible. :-) So really thanks for your feedback.

> If you keep both forms separate, you can still treat duplicate registrations as an attempt to password reset, store the hashed password in a temporary place, and have the user confirm the change by email.

That is a good proposal. I am trying to remove the need for them to make a decision "do I have an account here already or not" though. (But I am not sure if it is a good solution to remove that decision. It is currently my intuition after observing issues some users had using authentication on some other projects.)

> So a failed login doesn't cause unnecessary noise on the user

That is a good point.

Anyway, we are getting too specific about my own system here and maybe we should move this elsewhere, feel free to chime in at https://gitlab.com/charon/charon (project is still in early stages and not yet pushed). Thank you.

Trying to tie this back in to OPAQUE:

> Applying this to the OPAQUE protocol, ...

That is a great proposal and should probably be documented somewhere (e.g., that registration enumeration can be prevented by linking it to another verification, like e-mail address verification, before anything is leaked).

But I think combining both login and registration in OPAQUE could still be possible with simply registration be done every time, and simply both login and registration messages be send at the same time to the server, if login is correct, registration is discarded, otherwise the flow you proposed above is attempted.

**Comment by chris-wood** [comment] 2023-03-21 11:44
@mitar I'm sorry for the delay here. My take is that we should _not_ remove user enumeration support in the draft, as (a) that would be a fairly invasive and breaking change, and (b) it is possible to implement registration such that it does not easily allow enumeration (perhaps by using the "go check your email for a link" method above, or similar). As we worked on this document, we tried to carefully balance the diversity of threat models in which this protocol might be deployed and concluded that what's currently in the draft was a reasonable balance of real world considerations.

@kevinlewi, @bytemare: what do you think?

**Comment by kevinlewi** [comment] 2023-03-22 08:43
I believe the original purpose behind giving instructions for handling client enumeration was to match parity against a "normal password login form", where the client hashes the password and sends it to the server over a secure channel. In normal password login, the client sends a single message to the server, which the server then takes and can output whether or not the password matched registration for that user. This gives the server the ability to obscure whether or not a wrong password was entered for a registered account, versus the account not being registered.

Now, when attempting to use OPAQUE for a password login form, one big difference is that login now takes multiple steps, where the server must send a response to the client that could leak whether or not the user was registered. Therefore, a server that implements OPAQUE (without the fake credential responses) would no longer have the ability to obscure the existence of a registration, should they desire to do so. This was the purpose of introducing the fake credential responses -- so that we could give servers this option that exists in the normal flow.

However, in the normal password login flow (where registration isn't gated behind some other authentication mechanism), this information could still be leaked through registration. I don't think it is within our plans for this OPAQUE spec to try to go beyond what normal password login flows achieve.

So if there is an application that does want to try to prevent user enumeration through registration, I believe it should be handled outside of the scope of the OPAQUE protocol. And one way that sounds viable for addressing this is to combine the registration and login flows.

**Comment by chris-wood** [comment] 2023-03-22 12:55
@kevinlewi would you be supportive of adding text to the Application Considerations section that touches on this?

**Comment by kevinlewi** [comment] 2023-04-16 20:25
Closing this issue as resolved (but feel free to reopen if it isn't).

**Closed by kevinlewi** 2023-04-16 20:25 UTC
